[package]
name = "orchest-core"
version = "0.1.0-alpha.4"
edition.workspace = true

[dependencies]
orchest-platform = { path = "../orchest-platform" }
orchest-packages = { path = "../orchest-packages" }
orchest-process = { path = "../orchest-process" }
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
thiserror.workspace = true
uuid.workspace = true
chrono.workspace = true
rusqlite.workspace = true

[dev-dependencies]
tempfile.workspace = true
