[package]
name = "orchest-packages"
version = "0.1.0-alpha.4"
edition.workspace = true

[dependencies]
serde.workspace = true
toml.workspace = true
thiserror.workspace = true
reqwest.workspace = true
zip.workspace = true
tar.workspace = true
flate2.workspace = true
tempfile.workspace = true
orchest-platform = { path = "../orchest-platform" }
