[package]
name = "orchest-api"
version = "0.1.0-alpha.4"
edition.workspace = true

[dependencies]
orchest-core = { path = "../orchest-core" }
orchest-platform = { path = "../orchest-platform" }
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
